# Generated by Django 4.2.7 on 2023-12-03 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(default='Produto Padrão', max_length=255)),
                ('descricao_produto', models.TextField()),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_produto', models.PositiveIntegerField()),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='imagens_produtos/')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
